name: 'dbt_demo'
version: '1.0.0'
config-version: 2

profile: 'dbt_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  +docs:
    node_color: '#cd7f32'

models:
  dbt_demo:
    materialized: table
    staging:
      materialized: view
      +docs:
        node_color: 'silver'
    +docs:
      node_color: 'gold'
